# Generated by Django 4.1.3 on 2022-12-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('kullaniciAdi', models.CharField(max_length=15)),
                ('eposta', models.EmailField(max_length=254)),
                ('aciklama', models.CharField(max_length=300)),
            ],
        ),
    ]
