# Generated by Django 4.1.3 on 2022-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('aciklama', models.TextField(max_length=150)),
                ('fiyat', models.IntegerField()),
            ],
        ),
    ]
