# Generated by Django 4.1.3 on 2022-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fotograf',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
