# Generated by Django 4.1.3 on 2022-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urun_fotograf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='fotograf',
            field=models.FileField(upload_to='urunler'),
        ),
    ]
