# Generated by Django 4.1.3 on 2022-12-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_alter_urun_fotograf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='fotograf',
            field=models.FileField(blank=True, null=True, upload_to='urunler/'),
        ),
    ]
