# Generated by Django 4.1.3 on 2022-12-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
